import './globals.css'
import Header from "@/components/layout/header";
import Sidebar from "@/components/layout/sidebar";
import "../public/assets/css/nifty.css";
import "../public/assets/css/bootstrap.css";
import Script from 'next/script'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Portal</title>
        <Script src="/assets/vendors/popperjs/popper.min.js" defer />
        <Script src="/assets/vendors/bootstrap/bootstrap.min.js" defer />
        <Script src="/assets/js/nifty.js" defer />
      </head>
      <body className='jumping'>
        <div id="root" className="root mn--max hd--expanded">
          <Header />
          <Sidebar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  )
}
